name: Publish Bosch Thermostat Client 🐍 distributions 📦 to PyPI

on:
  push:
    tags:
      - v*
    branches:
      - 'dev'
    paths:
      - '**.py'
  pull_request:
    branches: [dev]
  release:
    types: # This configuration does not affect the page_build event above
      - created
      - edited

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pdm-project/setup-pdm@v3
        name: Setup Python and PDM
        with:
          python-version: '3.10'
          architecture: x64
          # version: 1.15.3
          enable-pep582: true # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: |
          python -m pip install -U twine
      - name: Build
        run: |
          pdm build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags') || startsWith(github.event.inputs.tags, 'Deploy')
        run: |
          pdm plugin add pdm-publish
          pdm publish -v --password ${{ secrets.PYPI_API_TOKEN }}
